version: '3.7'
services:
   gmail_api:
      build: ./
      hostname: gmail_api
#      stdin_open: true
#      tty: true
      env_file:
         - ./.env
      volumes:
        - ./keys:/app/keys